\ ============================================================================
\ STACK TESTS
\ Tests for stack manipulation primitives
\ ============================================================================

\ Note: This file is meant to be INCLUDEd by run-all.fth
\ If running standalone, you need to INCLUDE test/testing.fth and call INIT-TESTS first

S" stack.fth" TEST-FILE

TEST
5 3 NIP 3 EXPECT
S" NIP" TEST-NAME

TEST
5 10 TUCK 10 EXPECT 5 EXPECT 10 EXPECT
S" TUCK" TEST-NAME

TEST
1 2 3 2DROP 1 EXPECT
S" 2DROP" TEST-NAME

TEST
1 2 3 4 5 6 3DROP 3 EXPECT 2 EXPECT 1 EXPECT
S" 3DROP" TEST-NAME

TEST
1 2 3 3DUP 3 EXPECT 2 EXPECT 1 EXPECT 3 EXPECT 2 EXPECT 1 EXPECT
S" 3DUP" TEST-NAME

TEST
5 10 2DUP 10 EXPECT 5 EXPECT 10 EXPECT 5 EXPECT
S" 2DUP" TEST-NAME

TEST
0 ?DUP 0 EXPECT
S" ?DUP (zero)" TEST-NAME

TEST
5 ?DUP 5 EXPECT 5 EXPECT
S" ?DUP (positive)" TEST-NAME

TEST
-5 ?DUP -5 EXPECT -5 EXPECT
S" ?DUP (negative)" TEST-NAME

TEST
1 2 3 -ROT 2 EXPECT 1 EXPECT 3 EXPECT
S" -ROT" TEST-NAME

TEST
1 2 3 4 2OVER 2 EXPECT 1 EXPECT 4 EXPECT 3 EXPECT 2 EXPECT 1 EXPECT
S" 2OVER" TEST-NAME

TEST
1 2 3 4 2SWAP 2 EXPECT 1 EXPECT 4 EXPECT 3 EXPECT
S" 2SWAP" TEST-NAME

TEST
1 2 3 4 5 2 PICK 3 EXPECT 5 EXPECT 4 EXPECT 3 EXPECT 2 EXPECT 1 EXPECT
S" PICK - basic 2 PICK" TEST-NAME

TEST
10 20 30 0 PICK 30 EXPECT 30 EXPECT 20 EXPECT 10 EXPECT
S" PICK - 0 PICK" TEST-NAME

TEST
100 200 300 400 3 PICK 100 EXPECT 400 EXPECT 300 EXPECT 200 EXPECT 100 EXPECT
S" PICK - 3 PICK" TEST-NAME

TEST
1 2 3 4 5 4 PICK 1 EXPECT 5 EXPECT 4 EXPECT 3 EXPECT 2 EXPECT 1 EXPECT
S" PICK - 4 PICK (deep)" TEST-NAME
